In [2]:
import numpy as np


In [3]:
np.absolute(-5)

5

In [6]:
a=np.array([[1,2,3,4],[5,6,7]])
print(a)
print(type(a))
print(a.shape)

[list([1, 2, 3, 4]) list([5, 6, 7])]
<class 'numpy.ndarray'>
(2,)


In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
a.shape

(2, 4)

In [21]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [24]:
np.dot(a.T,a)

array([[26, 32, 38, 44],
       [32, 40, 48, 56],
       [38, 48, 58, 68],
       [44, 56, 68, 80]])

In [29]:
matrix = np.random.randint(60,100,(5,5))
print(matrix)


[[93 77 77 61 94]
 [74 69 89 68 75]
 [87 66 90 94 81]
 [96 72 84 69 96]
 [91 69 96 91 61]]


In [30]:
np.max(matrix)

96

In [32]:
np.min(matrix)

61

In [34]:
np.argmax(matrix)

15

In [37]:
b = np.unique(matrix,return_counts = True)
print(b[0])
print(b[1])

[61 66 68 69 72 74 75 77 81 84 87 89 90 91 93 94 96]
[2 1 1 3 1 1 1 2 1 1 1 1 1 2 1 2 3]


In [38]:
idx = np.argmax(b[1])
element = b[0][idx]
print(element)

69


In [39]:
matrix

array([[93, 77, 77, 61, 94],
       [74, 69, 89, 68, 75],
       [87, 66, 90, 94, 81],
       [96, 72, 84, 69, 96],
       [91, 69, 96, 91, 61]])

In [40]:
matrix[2:4,1:4]

array([[66, 90, 94],
       [72, 84, 69]])

In [31]:
c = np.zeros((2,3),dtype = np.int64)
print(c)
print(c[:,1:3])

[[0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]]


In [32]:
print(c.dtype)

int64


In [4]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
# print(np.min(a,axis=1))
# print(np.mean(a,axis=1),np.median(a))
wts = np.array([1,2,3,4])
print(np.mean(a))
print(np.average(a))
print(np.std(a))
print(np.var(a))

[[1 2 3 4]
 [7 6 2 0]]
3.125
3.125
2.2603926650031405
5.109375


In [16]:
x = np.array([[3,4],[6,8]])
lp2 = np.linalg.norm(x)
print(lp2)
lp1 = np.linalg.norm(x,ord =np.inf)
print(lp1)
print(np.linalg.det(x))

11.180339887498949
14.0
0.0


In [19]:
np.linalg.pinv(x)

array([[0.024, 0.048],
       [0.032, 0.064]])

In [29]:
a = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
print(np.linalg.norm(a))
# b =np.array([8,5])

6.0


In [25]:
np.linalg.solve(a,b)

array([0.7, 2.2])